// 지음 2.0 — Concept 노드 시드.
// 위키 항목 집필은 별도 콘텐츠 작업. 여기선 그래프 연결용 초안 10개만 둔다.
import type { Concept } from "@/lib/types";

export const concepts: Concept[] = [
  {
    id: "concept-human-in-the-loop",
    slug: "human-in-the-loop",
    titleKo: "휴먼 인 더 루프",
    titleEn: "Human-in-the-loop",
    summary: "AI 산출물의 품질은 사람의 검토 지점에서 결정된다. 어디에 사람을 끼울지 미리 정한다.",
    tags: ["literacy", "verification"],
    volatility: "evergreen",
    status: "draft",
  },
  {
    id: "concept-hallucination",
    slug: "hallucination",
    titleKo: "환각",
    titleEn: "Hallucination",
    summary: "LLM이 그럴듯하지만 근거 없는 답을 만들어내는 현상. 검증 습관으로 통제한다.",
    tags: ["literacy", "verification"],
    volatility: "evergreen",
    status: "draft",
  },
  {
    id: "concept-prompt-structure",
    slug: "prompt-structure",
    titleKo: "프롬프트 구조",
    titleEn: "Prompt Structure",
    summary: "작업·맥락·제약·출력 형식을 분리해 쓰는 명세적 프롬프트 작성법.",
    tags: ["prompt"],
    volatility: "evergreen",
    status: "draft",
  },
  {
    id: "concept-context-engineering",
    slug: "context-engineering",
    titleKo: "컨텍스트 엔지니어링",
    titleEn: "Context Engineering",
    summary: "긴 문서·파일을 모델 맥락에 효과적으로 주입·관리하는 설계.",
    tags: ["prompt"],
    volatility: "evolving",
    status: "draft",
  },
  {
    id: "concept-rag",
    slug: "rag",
    titleKo: "검색 증강 생성(RAG)",
    titleEn: "Retrieval-Augmented Generation",
    summary: "외부 문서를 검색해 근거와 함께 답하게 하는 패턴. '근거 있는 AI'의 실용형.",
    tags: ["rag"],
    volatility: "evolving",
    status: "draft",
  },
  {
    id: "concept-embedding",
    slug: "embedding",
    titleKo: "임베딩",
    titleEn: "Embedding",
    summary: "텍스트를 의미 벡터로 바꾼 표현. 벡터 검색의 기반.",
    tags: ["rag"],
    volatility: "evergreen",
    status: "draft",
  },
  {
    id: "concept-tool-use",
    slug: "tool-use",
    titleKo: "도구 사용(Tool Use)",
    titleEn: "Tool Use",
    summary: "모델이 함수·외부 도구를 호출해 작업을 수행하게 하는 메커니즘.",
    tags: ["agents"],
    volatility: "evolving",
    status: "draft",
  },
  {
    id: "concept-agent-loop",
    slug: "agent-loop",
    titleKo: "에이전트 루프",
    titleEn: "Agent Loop",
    summary: "사고·행동·관찰을 반복하며 목표에 도달하는 에이전트의 실행 구조.",
    tags: ["agents"],
    volatility: "evolving",
    status: "draft",
  },
  {
    id: "concept-prompt-injection",
    slug: "prompt-injection",
    titleKo: "프롬프트 인젝션",
    titleEn: "Prompt Injection",
    summary: "외부 입력으로 모델 지시를 탈취하는 공격. 권한 설계와 입력 분리로 방어한다.",
    tags: ["security"],
    volatility: "evergreen",
    status: "draft",
  },
  {
    id: "concept-evals",
    slug: "evals",
    titleKo: "평가(Evals)",
    titleEn: "Evals",
    summary: "AI 출력 품질을 재현 가능하게 측정하는 테스트 세트.",
    tags: ["evals"],
    volatility: "evergreen",
    status: "draft",
  },
];
