import type { Phase } from "@/lib/types";

export const phases: Phase[] = [
  {
    id: "phase-0",
    slug: "phase-0-setup",
    order: 0,
    titleKo: "AI 학습 환경 세팅",
    titleEn: "Learning Environment Setup",
    shortDescription: "Codex / Claude Code / GitHub / API 키를 실습 가능한 상태로 준비한다.",
    longDescription:
      "AI Builder School의 모든 레슨은 코딩 에이전트를 도구로 쓴다. 이 Phase에서는 로컬 개발 환경, Codex CLI 또는 Claude Code, GitHub 저장소, 그리고 API 키 관리 방식을 한 번에 정돈한다. 완료 시점에 모든 후속 레슨이 그대로 실행 가능해야 한다.",
    level: "beginner",
    estimatedHours: 4,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "Codex CLI 또는 Claude Code를 로컬에서 실행할 수 있다",
      "개인 실습용 저장소 `my-ai-builder-lab`를 생성한다",
      "API 키를 안전하게 저장하는 습관을 잡는다",
    ],
    topics: [
      "Codex CLI / Claude Code 설치",
      "GitHub 저장소 초기화",
      "터미널 기초",
      "환경 변수 & .env 관리",
      "도구 선택 가이드",
    ],
    deliverables: [
      "my-ai-builder-lab GitHub 저장소",
      "코딩 에이전트 워크플로우 템플릿",
      "환경 변수 체크리스트",
    ],
    lessonSlugs: [
      "zero-coding-orientation",
      "terminal-first-day",
      "ai-tool-account-and-cost",
      "privacy-and-academic-ethics",
    ],
    recommendedTools: ["Codex CLI", "Claude Code", "GitHub", "VS Code"],
    nextPhaseSlug: "phase-1-ai-literacy",
    weekInMvpPath: null,
  },
  {
    id: "phase-1",
    slug: "phase-1-ai-literacy",
    order: 1,
    titleKo: "AI Literacy",
    titleEn: "AI Literacy",
    shortDescription: "AI를 맹신하지 않고, 판단 기준과 한계를 먼저 이해한다.",
    longDescription:
      "모든 학습은 '무엇을 신뢰하고, 무엇을 검증해야 하는가'에서 출발한다. 이 Phase에서는 LLM의 작동 원리 최소치, 환각(Hallucination), 프라이버시·저작권 이슈, 휴먼 인 더 루프(Human-in-the-loop) 원칙을 다룬다. 목표는 '똑똑해 보이는 답'을 경계하고 '근거 있는 답'을 요구할 수 있는 안목을 만드는 것이다.",
    level: "beginner",
    estimatedHours: 6,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "LLM이 잘하는 일과 못하는 일의 경계를 안다",
      "AI 출력에 대한 자기 검증 루틴을 만든다",
      "조직·개인에 맞는 AI 사용 판단 체크리스트를 갖는다",
    ],
    topics: [
      "LLM 기초",
      "환각과 검증",
      "프라이버시 / 저작권",
      "Human-in-the-loop",
      "AI 윤리와 과의존",
    ],
    deliverables: ["AI 사용 판단 체크리스트 v1"],
    lessonSlugs: [
      "common-skills-of-future-proof-people",
      "ai-concept-learning-framework",
      "what-llms-are-good-and-bad-at",
      "hallucination-verification",
      "checks-before-trusting-ai-output",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Perplexity"],
    nextPhaseSlug: "phase-2-prompt-engineering",
    weekInMvpPath: 1,
  },
  {
    id: "phase-2",
    slug: "phase-2-prompt-engineering",
    order: 2,
    titleKo: "Prompt & Context Engineering",
    titleEn: "Prompt & Context Engineering",
    shortDescription: "모호한 질문을 재현 가능한 작업지시서로 바꾼다.",
    longDescription:
      "좋은 프롬프트는 '부탁'이 아니라 '명세(Spec)'다. 이 Phase에서는 작업/맥락/제약/출력 형식을 분리해 쓰는 법, 긴 문서를 분할해 주입하는 법, 구조화 출력을 강제하는 법을 연습한다. 최종 산출물은 자신만의 프롬프트 라이브러리다.",
    level: "beginner",
    estimatedHours: 8,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "작업/맥락/제약/출력 형식을 분리해 프롬프트를 쓴다",
      "긴 문맥을 파일 기반으로 주입한다",
      "개인용 프롬프트 라이브러리를 운영한다",
    ],
    topics: [
      "프롬프트 구조",
      "예시(Few-shot) 활용",
      "출력 포맷 강제",
      "긴 문서 처리",
      "파일 기반 워크플로우",
    ],
    deliverables: ["개인 프롬프트 라이브러리(JSON or Notion)"],
    lessonSlugs: [
      "structure-of-good-prompts",
      "enforcing-output-format",
      "feeding-long-documents",
      "build-personal-prompt-library",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Markdown"],
    nextPhaseSlug: "phase-3-ai-work-os",
    weekInMvpPath: 2,
  },
  {
    id: "phase-3",
    slug: "phase-3-ai-work-os",
    order: 3,
    titleKo: "AI Work OS",
    titleEn: "AI Work OS",
    shortDescription: "보고서·회의록·리서치·글쓰기를 AI로 운영한다.",
    longDescription:
      "개인의 일상 업무를 AI 파이프라인으로 바꾸는 단계다. 보고서 초안, 회의록 정리, 심층 리서치, 블로그/이메일 파이프라인을 만든다. '나만의 AI 업무 플레이북'이 산출물이다.",
    level: "beginner",
    estimatedHours: 10,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "explorer"],
    outcomes: [
      "보고서/회의록/리서치/글쓰기를 AI로 반복 생산한다",
      "개인 AI 업무 플레이북을 만든다",
      "반복 업무를 템플릿으로 정리한다",
    ],
    topics: ["보고서 초안", "회의록", "리서치", "이메일/문서", "스프레드시트 분석"],
    deliverables: ["개인 AI 업무 플레이북"],
    lessonSlugs: [
      "automate-report-drafts",
      "meeting-notes-pipeline",
      "research-workflow",
      "blog-writing-pipeline",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Google Docs"],
    nextPhaseSlug: "phase-4-coding-agents",
    weekInMvpPath: 3,
  },
  {
    id: "phase-4",
    slug: "phase-4-coding-agents",
    order: 4,
    titleKo: "Codex / Claude Code Workflow",
    titleEn: "Codex / Claude Code Workflow",
    shortDescription: "코딩 에이전트를 페어 프로그래머·리뷰어·테스터로 길들인다.",
    longDescription:
      "이 Phase에서는 코딩 에이전트를 '자동완성'이 아닌 협업 팀원으로 다룬다. 이슈를 작업지시서로 바꾸고, 구현 계획을 함께 세우고, 테스트를 만들고, 버그를 재현·수정하는 루프를 습관화한다.",
    level: "intermediate",
    estimatedHours: 12,
    targetJourneys: ["engineer", "founder"],
    outcomes: [
      "GitHub Issue → 구현 계획 → diff → 리뷰 루프를 정착",
      "코드베이스 탐색을 AI에게 위임",
      "AI 작성 코드에 대한 자기 리뷰 기준을 가짐",
    ],
    topics: [
      "에이전트 작업 환경",
      "이슈-투-플랜",
      "diff 리뷰",
      "테스트 작성",
      "리팩터링",
      "버그 재현",
    ],
    deliverables: ["코딩 에이전트 개발 루틴 문서"],
    lessonSlugs: [
      "coding-agent-setup",
      "claude-md-four-principles",
      "github-issue-to-ai-brief",
      "letting-ai-read-codebase",
      "plan-with-ai",
      "write-tests-with-coding-agent",
      "bug-reproduction-loop",
      "harness-engineering-roadmap",
    ],
    recommendedTools: ["Codex CLI", "Claude Code", "GitHub", "Playwright"],
    nextPhaseSlug: "phase-5-ai-app-dev",
    weekInMvpPath: 4,
  },
  {
    id: "phase-5",
    slug: "phase-5-ai-app-dev",
    order: 5,
    titleKo: "AI App Development",
    titleEn: "AI App Development",
    shortDescription: "AI를 호출하는 작은 웹앱을 직접 만들고 배포한다.",
    longDescription:
      "AI API를 붙여 실제로 작동하는 앱을 만든다. 스트리밍 UI, 구조화 출력, 대화 저장, 배포까지 이어진다. '작지만 쓸만한' MVP를 손으로 만든다.",
    level: "intermediate",
    estimatedHours: 16,
    targetJourneys: ["engineer", "founder"],
    outcomes: [
      "AI API를 앱에 안전하게 연결한다",
      "스트리밍/구조화 출력 UX를 구현한다",
      "작은 AI 웹앱을 실제 배포한다",
    ],
    topics: ["AI API", "스트리밍", "구조화 출력", "인증 기초", "DB 기초", "배포"],
    deliverables: ["배포된 AI 웹앱 MVP"],
    lessonSlugs: [
      "connect-ai-api",
      "streaming-response-ui",
      "structured-output-handling",
      "conversation-storage-design",
    ],
    recommendedTools: ["Next.js", "Vercel", "OpenAI / Anthropic SDK"],
    nextPhaseSlug: "phase-6-rag",
    weekInMvpPath: 5,
  },
  {
    id: "phase-6",
    slug: "phase-6-rag",
    order: 6,
    titleKo: "Data, Embedding & RAG",
    titleEn: "Data, Embedding & RAG",
    shortDescription: "내가 가진 문서에 답하는 AI를 만든다.",
    longDescription:
      "RAG(Retrieval-Augmented Generation)는 '근거 있는 AI'의 가장 실용적인 형태다. 청킹 전략, 임베딩 저장, 벡터 검색, 인용 제공, 품질 평가를 다룬다.",
    level: "intermediate",
    estimatedHours: 14,
    targetJourneys: ["engineer", "founder"],
    outcomes: [
      "문서를 RAG에 맞게 청킹한다",
      "벡터 검색 + 인용으로 답하는 기본 파이프라인을 만든다",
      "RAG 품질을 스스로 평가한다",
    ],
    topics: ["임베딩", "청킹", "벡터 검색", "메타데이터", "인용", "RAG 평가"],
    deliverables: ["문서 Q&A 봇"],
    lessonSlugs: [
      "understanding-embeddings",
      "document-chunking-strategy",
      "vector-search-basics",
      "grounded-rag-answers",
    ],
    recommendedTools: ["OpenAI Embeddings", "Pinecone / pgvector", "LangChain / LlamaIndex"],
    nextPhaseSlug: "phase-7-agents-mcp",
    weekInMvpPath: 6,
  },
  {
    id: "phase-7",
    slug: "phase-7-agents-mcp",
    order: 7,
    titleKo: "Tool Use, Agents & MCP",
    titleEn: "Tool Use, Agents & MCP",
    shortDescription: "AI가 도구를 안전하게 쓰도록 에이전트를 설계한다.",
    longDescription:
      "Function calling, 에이전트 루프, 메모리, 계획 수립, MCP(Model Context Protocol), 권한 설계를 다룬다. '쓸만하면서도 선을 지키는' 에이전트를 목표로 한다.",
    level: "advanced",
    estimatedHours: 14,
    targetJourneys: ["engineer", "founder"],
    outcomes: [
      "Function calling 기반 미니 에이전트를 만든다",
      "도구 권한과 안전장치를 설계한다",
      "Prompt injection 기본 방어를 구현한다",
    ],
    topics: [
      "Function calling",
      "에이전트 루프",
      "메모리",
      "MCP",
      "권한 / 샌드박싱",
      "프롬프트 인젝션",
    ],
    deliverables: ["미니 워크플로우 에이전트"],
    lessonSlugs: [
      "function-calling",
      "mini-agent-loop",
      "ralph-loop-codex-goal",
      "tool-permission-safeguards",
      "prompt-injection-defense",
    ],
    recommendedTools: ["Claude Tools", "OpenAI Tools", "MCP SDK"],
    nextPhaseSlug: "phase-8-multimodal",
    weekInMvpPath: 7,
  },
  {
    id: "phase-8",
    slug: "phase-8-multimodal",
    order: 8,
    titleKo: "Multimodal AI & Content Automation",
    titleEn: "Multimodal AI & Content Automation",
    shortDescription: "텍스트·이미지·오디오·비디오를 잇는 파이프라인을 만든다.",
    longDescription:
      "크리에이터의 워크플로우를 AI 파이프라인으로 바꾼다. 이미지 프롬프트, 음성/자막, 블로그→쇼츠 파이프라인을 다룬다.",
    level: "intermediate",
    estimatedHours: 10,
    targetJourneys: ["creator"],
    outcomes: [
      "블로그-쇼츠 연결 파이프라인을 만든다",
      "이미지/오디오 프롬프트를 재현 가능하게 관리한다",
    ],
    topics: ["이미지 프롬프트", "음성", "자막", "비디오 스크립트", "콘텐츠 파이프라인"],
    deliverables: ["콘텐츠 자동화 파이프라인 1개"],
    lessonSlugs: ["blog-to-shorts-pipeline", "design-visual-prompt-system", "youtube-script-research-to-outline", "figma-ai-ui-variation-workflow", "thumbnail-and-title-ab-test", "local-business-content-calendar"],
    recommendedTools: ["Midjourney", "ElevenLabs", "Runway", "Capcut"],
    nextPhaseSlug: "phase-9-data-decision",
    weekInMvpPath: null,
  },
  {
    id: "phase-9",
    slug: "phase-9-data-decision",
    order: 9,
    titleKo: "Data Analysis & Decision AI",
    titleEn: "Data Analysis & Decision AI",
    shortDescription: "데이터 분석과 의사결정 보조에 AI를 투입한다.",
    longDescription:
      "CSV, 스프레드시트, SQL, 대시보드, 의사결정 메모를 AI와 함께 다룬다. 분석 보조와 판단 보조의 경계를 의식적으로 구분한다.",
    level: "intermediate",
    estimatedHours: 10,
    targetJourneys: ["adopter", "practitioner", "founder"],
    outcomes: [
      "엑셀/CSV 분석을 AI에게 위임한다",
      "시나리오 분석과 의사결정 메모를 생산한다",
    ],
    topics: ["CSV / Excel", "SQL", "대시보드", "시나리오 분석", "의사결정 메모"],
    deliverables: ["AI 분석 노트북 또는 리포트 생성기"],
    lessonSlugs: [
      "sql-with-ai-verification",
      "crm-segmentation-with-ai",
      "dashboard-narrative-and-qa",
      "ab-test-decision-memo",
    ],
    recommendedTools: ["Python", "Jupyter", "Claude", "Excel"],
    nextPhaseSlug: "phase-10-evals-security",
    weekInMvpPath: null,
  },
  {
    id: "phase-10",
    slug: "phase-10-evals-security",
    order: 10,
    titleKo: "Evals, Security & Responsible AI",
    titleEn: "Evals, Security & Responsible AI",
    shortDescription: "AI 시스템을 안전하고 검증 가능하게 만든다.",
    longDescription:
      "평가(Evals), 환각 테스트, 프롬프트 인젝션, 프라이버시, 로깅/모니터링, 과의존 문제를 다룬다. 배포 전 점검 체크리스트를 만든다.",
    level: "advanced",
    estimatedHours: 10,
    targetJourneys: ["engineer", "adopter", "founder"],
    outcomes: [
      "자체 eval 세트를 만든다",
      "프롬프트 인젝션 방어를 이해한다",
      "배포 전 체크리스트를 운영한다",
    ],
    topics: ["Evals", "환각 테스트", "프롬프트 인젝션", "프라이버시", "로깅", "과의존"],
    deliverables: ["AI 품질·보안 체크리스트"],
    lessonSlugs: [
      "evals-for-ai-coded-prs",
      "llm-observability-and-regression",
      "ai-output-eval-for-pms",
      "responsible-ai-policy-template",
    ],
    recommendedTools: ["Evals SDK", "Promptfoo", "Langfuse"],
    nextPhaseSlug: "phase-11-product",
    weekInMvpPath: null,
  },
  {
    id: "phase-11",
    slug: "phase-11-product",
    order: 11,
    titleKo: "AI Product & Monetization",
    titleEn: "AI Product & Monetization",
    shortDescription: "AI 스킬을 제품과 수익으로 바꾼다.",
    longDescription:
      "문제 발굴, MVP, 랜딩, 가격, 리텐션, 배포, B2B/B2C를 다룬다. 제품으로 가는 최소한의 길을 설계한다.",
    level: "intermediate",
    estimatedHours: 10,
    targetJourneys: ["adopter", "founder", "creator"],
    outcomes: [
      "AI 제품 브리프를 만든다",
      "런칭 계획을 수립한다",
    ],
    topics: ["문제 발굴", "MVP", "랜딩", "가격", "리텐션", "배포"],
    deliverables: ["AI 제품 브리프 + 런칭 계획"],
    lessonSlugs: [
      "ai-app-cost-and-usage",
      "claude-code-token-saving",
      "ai-product-brief",
      "landing-page-for-ai-product",
      "pricing-and-monetization",
    ],
    recommendedTools: ["Framer", "Vercel", "Stripe"],
    nextPhaseSlug: "phase-12-capstone",
    weekInMvpPath: null,
  },
  {
    id: "phase-12",
    slug: "phase-12-capstone",
    order: 12,
    titleKo: "Capstone Projects",
    titleEn: "Capstone Projects",
    shortDescription: "포트폴리오로 쓸 수 있는 AI 프로젝트를 끝까지 간다.",
    longDescription:
      "지금까지 쌓은 것을 합쳐 '진짜 공개할 수 있는 작은 제품'을 만든다. 기획, 구현, 검증, 런칭, 회고까지의 전 과정을 공개 저장소에 기록한다.",
    level: "advanced",
    estimatedHours: 20,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "배포된 AI 프로젝트 1개를 가진다",
      "공개 회고 문서 1개를 가진다",
    ],
    topics: ["기획", "구현", "검증", "런칭", "회고"],
    deliverables: ["배포된 AI 프로젝트", "공개 회고 문서"],
    lessonSlugs: [
      "capstone-plan-and-launch",
      "capstone-scope-selection",
      "capstone-build-loop",
      "portfolio-and-retrospective",
    ],
    recommendedTools: ["Next.js", "Vercel", "GitHub", "Notion"],
    nextPhaseSlug: null,
    weekInMvpPath: 8,
  },
];
