import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "project-doc-qa",
    slug: "document-qa-bot",
    title: "문서 Q&A 봇",
    targetLearner: "개발자·앱 빌더 / AI 엔지니어 심화",
    difficulty: "intermediate",
    requiredPhases: ["phase-2-prompt-engineering", "phase-5-ai-app-dev", "phase-6-rag"],
    finalOutput: "공개 URL로 배포된 문서 Q&A 웹앱 + 근거 스니펫 표시",
    suggestedStack: ["Next.js", "pgvector or Pinecone", "OpenAI / Anthropic"],
    summary: "내가 가진 PDF·노트를 업로드하면 출처와 함께 답하는 RAG 웹앱.",
  },
  {
    id: "project-meeting-bot",
    slug: "meeting-notes-bot",
    title: "회의록 자동 정리 봇",
    targetLearner: "일반 직장인 / 기획자·관리자",
    difficulty: "beginner",
    requiredPhases: ["phase-2-prompt-engineering", "phase-3-ai-work-os"],
    finalOutput: "녹취·메모 → 결정·Action Item 구조화된 회의록 파이프라인",
    suggestedStack: ["Google Drive", "Make / n8n", "Claude"],
    summary: "회의가 끝나면 자동으로 Action Item이 팀 툴에 도착한다.",
  },
  {
    id: "project-research-agent",
    slug: "personal-research-agent",
    title: "개인 리서치 에이전트",
    targetLearner: "기획자·관리자 / 개발자·앱 빌더",
    difficulty: "advanced",
    requiredPhases: [
      "phase-2-prompt-engineering",
      "phase-4-coding-agents",
      "phase-7-agents-mcp",
    ],
    finalOutput: "질문을 넣으면 웹 검색·요약·출처 정리까지 수행하는 에이전트",
    suggestedStack: ["Node.js", "Claude Tools", "SerpAPI"],
    summary: "리서치 질문을 분해하고 출처와 함께 보고서를 돌려주는 에이전트.",
  },
  {
    id: "project-content-pipeline",
    slug: "blog-to-shortform",
    title: "블로그→쇼츠 자동 파이프라인",
    targetLearner: "콘텐츠 크리에이터",
    difficulty: "intermediate",
    requiredPhases: [
      "phase-2-prompt-engineering",
      "phase-3-ai-work-os",
      "phase-8-multimodal",
    ],
    finalOutput: "블로그 글 1편 → 쇼츠 스크립트/이미지 브리프/스크립트 자동 생성",
    suggestedStack: ["Notion", "ChatGPT", "Midjourney", "Runway"],
    summary: "긴 글 하나를 여러 채널 포맷으로 재가공하는 파이프라인.",
  },
  {
    id: "project-rag-analytics",
    slug: "rag-with-evals",
    title: "Evals 대시보드가 붙은 RAG",
    targetLearner: "AI 엔지니어 심화",
    difficulty: "advanced",
    requiredPhases: [
      "phase-6-rag",
      "phase-10-evals-security",
      "phase-12-capstone",
    ],
    finalOutput: "품질·비용·안전성을 관찰 가능한 RAG 서비스 + 대시보드",
    suggestedStack: ["Next.js", "pgvector", "Promptfoo", "Langfuse"],
    summary: "단순 RAG를 넘어 품질과 비용을 지속적으로 관찰 가능한 형태로 만든다.",
  },
  {
    id: "project-onboarding-bot",
    slug: "team-onboarding-bot",
    title: "팀 온보딩 봇",
    targetLearner: "기획자·관리자 / 개발자·앱 빌더",
    difficulty: "intermediate",
    requiredPhases: [
      "phase-2-prompt-engineering",
      "phase-5-ai-app-dev",
      "phase-6-rag",
    ],
    finalOutput: "신규 입사자를 위한 사내 Q&A 봇(RAG + 접근 제어)",
    suggestedStack: ["Next.js", "pgvector", "Supabase Auth"],
    summary: "신규 입사자가 사내 문서와 FAQ에 자연어로 질문할 수 있게 한다.",
  },
];
