// 캡스톤·포트폴리오용 프로젝트 카탈로그.
// v0.4 — requiredStages(Stage 모델) 기준.
// 난이도 순으로 정렬 — 입문자가 /projects 첫 화면에서 자기 수준 프로젝트를 먼저 본다.
import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "project-meeting-bot",
    slug: "meeting-notes-bot",
    title: "회의록 자동 정리 봇",
    targetLearner: "실무자·도입자·탐험가 — 코딩 없이 시작하는 첫 자동화",
    targetJourneys: ["practitioner", "adopter", "explorer"],
    difficulty: "beginner",
    requiredStages: ["stage-2-ask", "stage-4-collaborate"],
    finalOutput: "녹취·메모 → 결정·Action Item 구조화된 회의록 파이프라인",
    suggestedStack: ["Google Drive", "Make / n8n", "Claude"],
    summary: "회의가 끝나면 자동으로 Action Item이 팀 툴에 도착한다. 코딩 없이 만드는 첫 빌더 프로젝트.",
  },
  {
    id: "project-content-pipeline",
    slug: "blog-to-shortform",
    title: "블로그→쇼츠 자동 파이프라인",
    targetLearner: "크리에이터 — 콘텐츠 한 편을 여러 채널 포맷으로",
    targetJourneys: ["creator"],
    difficulty: "intermediate",
    requiredStages: ["stage-2-ask", "stage-4-collaborate"],
    finalOutput: "블로그 글 1편 → 쇼츠 스크립트/이미지 브리프/뉴스레터 자동 생성",
    suggestedStack: ["Notion", "ChatGPT", "Midjourney", "Runway"],
    summary: "긴 글 하나를 여러 채널 포맷으로 재가공하는 파이프라인.",
  },
  {
    id: "project-doc-qa",
    slug: "document-qa-bot",
    title: "문서 Q&A 봇",
    targetLearner: "엔지니어·파운더 — 내 문서에 답하는 첫 RAG 앱",
    targetJourneys: ["engineer", "founder"],
    difficulty: "intermediate",
    requiredStages: ["stage-2-ask", "stage-6-build"],
    finalOutput: "공개 URL로 배포된 문서 Q&A 웹앱 + 근거 스니펫 표시",
    suggestedStack: ["Next.js", "pgvector or Pinecone", "OpenAI / Anthropic"],
    summary: "내가 가진 PDF·노트를 업로드하면 출처와 함께 답하는 RAG 웹앱.",
  },
  {
    id: "project-onboarding-bot",
    slug: "team-onboarding-bot",
    title: "팀 온보딩 봇",
    targetLearner: "도입자·파운더·엔지니어 — 사내 지식을 봇으로",
    targetJourneys: ["adopter", "founder", "engineer"],
    difficulty: "intermediate",
    requiredStages: ["stage-2-ask", "stage-6-build"],
    finalOutput: "신규 입사자를 위한 사내 Q&A 봇(RAG + 접근 제어)",
    suggestedStack: ["Next.js", "pgvector", "Supabase Auth"],
    summary: "신규 입사자가 사내 문서와 FAQ에 자연어로 질문할 수 있게 한다.",
  },
  {
    id: "project-research-agent",
    slug: "personal-research-agent",
    title: "개인 리서치 에이전트",
    targetLearner: "엔지니어·파운더 — 도구를 쓰는 자율 에이전트",
    targetJourneys: ["engineer", "founder"],
    difficulty: "advanced",
    requiredStages: ["stage-2-ask", "stage-5-delegate", "stage-6-build"],
    finalOutput: "질문을 넣으면 웹 검색·요약·출처 정리까지 수행하는 에이전트",
    suggestedStack: ["Node.js", "Claude Tools", "SerpAPI"],
    summary: "리서치 질문을 분해하고 출처와 함께 보고서를 돌려주는 에이전트.",
  },
  {
    id: "project-rag-analytics",
    slug: "rag-with-evals",
    title: "Evals 대시보드가 붙은 RAG",
    targetLearner: "엔지니어 — 운영·평가까지 갖춘 RAG 시스템",
    targetJourneys: ["engineer"],
    difficulty: "advanced",
    requiredStages: ["stage-6-build", "stage-7-operate", "stage-8-share"],
    finalOutput: "품질·비용·안전성을 관찰 가능한 RAG 서비스 + 대시보드",
    suggestedStack: ["Next.js", "pgvector", "Promptfoo", "Langfuse"],
    summary: "단순 RAG를 넘어 품질과 비용을 지속적으로 관찰 가능한 형태로 만든다.",
  },
];
