// v2.0 — 6 Stage 데이터. 학습자 수직 진척 사다리.
// 2026-05-22 — 옛 8 Stage에서 6 Stage로 통합 (S2+S3 → 새 S2, S7+S8 → 새 S6).
// 매핑 원본: docs/specs/2026-05-22-six-stage-restructure-and-lesson-consolidation.md
import type { Stage } from "@/lib/types";

export const stages: Stage[] = [
  {
    id: "stage-1",
    slug: "stage-1-meet",
    order: 1,
    label: "AI와 만나다",
    titleKo: "Stage 1 · AI와 만나다",
    titleEn: "Meet AI",
    positionChange: "AI를 이해하고 도구를 손에 잡는다",
    deliverable: "매일 쓰는 AI 도구 1개 + 첫 git repo",
    shortDescription: "LLM이 뭔지부터 터미널·git·GitHub까지, AI를 일에 들이기 전에 알아야 할 원리와 도구를 한 사다리로 잡는다.",
    longDescription:
      "AI Builder가 되는 사다리의 첫 칸. 세 단계로 펼쳐진다. (1a) **원리** — LLM이 무엇이고, 토큰·맥락·비용은 어떻게 엮이고, 서비스는 어떻게 나뉘고, 챗봇의 기본 기능과 사람-AI 분업의 큰 그림. (1b) **도구·환경** — 코딩 에이전트가 왜 터미널을 쓰고, git/GitHub로 작업을 어떻게 안전망에 둬야 하며, 계정·API 키·비용을 어떻게 관리하는지. (1c) **판단** — 어떤 일을 AI에 맡길지, 사람으로 남는 협업 마인드셋. 끝나는 시점에 매일 쓰는 AI 도구 1개와 첫 git repo, 자기 업무용 위임 체크리스트가 손에 남는다.",
    level: "beginner",
    estimatedHours: 13,
    targetJourneys: ["practitioner", "creator", "founder", "engineer", "starter", "ai-native"],
    outcomes: [
      "LLM이 다음 토큰을 예측하는 기계임을 알고, 잘하는 일/못하는 일을 구분한다",
      "토큰·맥락·비용의 관계를 이해해 청구서 쇼크를 예방한다",
      "자기 모델 서비스와 API 애그리게이터의 차이를 알고 도구를 고른다",
      "터미널 기본 명령어 10개를 두려움 없이 사용한다",
      "git으로 작업을 시점 기록하고 GitHub에 첫 repo를 만든다",
      "AI 비용을 주간 루프로 모니터링하는 습관을 잡는다",
      "어떤 일을 AI에 맡길지 판단하는 개인 기준표를 갖는다",
    ],
    topics: [
      "LLM 원리·토큰·맥락·비용",
      "AI 서비스 지형·챗봇 공통 기능",
      "터미널·CLI 기초",
      "git·GitHub·.gitignore",
      "AI 도구 계정·비용 모니터링",
      "위임 판단 (AI Fluency Delegation)",
      "사람-AI 협업 마인드셋",
    ],
    lessonSlugs: [
      // 1a 원리
      "what-is-an-llm",
      "tokens-context-and-cost",
      "ai-service-landscape",
      "ai-chat-features-basics",
      "common-skills-of-future-proof-people",
      // 1b 도구·환경
      "zero-coding-orientation",
      "terminal-first-day",
      "git-basics-and-terminology",
      "github-essentials",
      "ai-tool-account-and-cost",
      "cost-monitoring-in-production",
      // 1c 함께 일하는 판단
      "ai-delegation-decision",
      "ai-collaboration-mindset",
    ],
    subGroups: [
      {
        id: "1a",
        label: "AI를 이해하다",
        shortDescription: "LLM·토큰·맥락·비용·서비스 지형·챗봇 기본 기능 — 터미널을 켜기 전에 AI 자체를 안다.",
        deliverable: "자기 말로 LLM 한 단락",
        lessonSlugs: [
          "what-is-an-llm",
          "tokens-context-and-cost",
          "ai-service-landscape",
          "ai-chat-features-basics",
          "common-skills-of-future-proof-people",
        ],
      },
      {
        id: "1b",
        label: "도구·환경을 손에 잡다",
        shortDescription: "터미널·git·GitHub·계정·비용 — 안전망 위에서 AI 도구를 매일 쓸 수 있는 환경을 만든다.",
        deliverable: "첫 git repo + AI 도구 1개",
        lessonSlugs: [
          "zero-coding-orientation",
          "terminal-first-day",
          "git-basics-and-terminology",
          "github-essentials",
          "ai-tool-account-and-cost",
          "cost-monitoring-in-production",
        ],
      },
      {
        id: "1c",
        label: "함께 일하는 판단",
        shortDescription: "어떤 일을 AI에 맡기고 무엇은 사람이 결정해야 하는지의 기준을 잡는다.",
        deliverable: "위임 체크리스트 v1",
        lessonSlugs: [
          "ai-delegation-decision",
          "ai-collaboration-mindset",
        ],
      },
    ],
    recommendedTools: ["Claude", "ChatGPT", "Codex CLI", "Claude Code", "git", "GitHub"],
    nextStageSlug: "stage-2-ask-and-refine",
    weekInMvpPath: 1,
    introEssaySlug: "stage-1-intro",
    outroEssaySlug: "stage-1-outro",
  },
  {
    id: "stage-2",
    slug: "stage-2-ask-and-refine",
    order: 2,
    label: "AI에게 묻고 답하다",
    titleKo: "Stage 2 · AI에게 묻고 답하다",
    titleEn: "Ask and Answer",
    positionChange: "의도한 답을 끌어내고 검증한다",
    deliverable: "프롬프트 라이브러리 + 검증 루프",
    shortDescription: "재현 가능한 명세로 묻고, 받은 답을 검증·다듬어 일관된 결과를 얻는다.",
    longDescription:
      "좋은 프롬프트는 부탁이 아니라 명세(spec)다. 일관되게 답한다고 해서 옳은 답은 아니다. 이 단계는 두 면을 같이 익힌다 — 묻는 면(프롬프트 4축·모델 종류·출력 형식·긴 문서·이미지·반복 루프·배치)과 다듬는 면(LLM 강약 지도·환각 검증·빠른 점검·차선책·안전 경계). 끝나는 시점에 재현 가능한 프롬프트 라이브러리 한 벌과 검증 루프 하나가 손에 남는다.",
    level: "beginner",
    estimatedHours: 19,
    targetJourneys: ["practitioner", "creator", "founder", "engineer", "starter", "ai-native"],
    outcomes: [
      "작업/맥락/제약/출력을 분리하고 모델 종류에 맞춰 프롬프트를 쓴다",
      "출력 형식을 강제하고, 실패한 프롬프트를 4축으로 진단한다",
      "긴 문서·이미지·음성을 프롬프트 입력으로 다룬다",
      "AI 출력을 평가하고 다듬으며, 반복 작업을 배치로 묶는다",
      "LLM이 잘하는 일과 못하는 일의 경계를 안다",
      "환각·오류를 잡는 검증 루프를 자기 워크플로우에 박는다",
      "검증에서 오류를 발견했을 때의 차선책을 미리 정해둔다",
      "프라이버시·저작권 같은 안전 경계를 자기 체크리스트로 갖는다",
      "재사용 가능한 프롬프트 라이브러리를 운영한다",
    ],
    topics: [
      "프롬프트 4축 구조",
      "모델 유형별 프롬프트",
      "출력 형식 강제·디버깅",
      "긴 문서·멀티모달 입력",
      "출력 평가·refine 루프",
      "배치 프롬프팅·비용",
      "LLM 능력의 한계",
      "환각 검증",
      "신뢰 전 5분 체크 (FOSCB)",
      "AI 실패 시 차선책",
      "프라이버시·윤리",
      "프롬프트 라이브러리",
    ],
    lessonSlugs: [
      // 묻는 면 (옛 Stage 2)
      "structure-of-good-prompts",
      "reasoning-vs-instruct-prompting",
      "enforcing-output-format",
      "prompt-debugging-loop",
      "feeding-long-documents",
      "multimodal-prompting",
      "output-evaluation-refine",
      "api-rate-limiting-and-batching",
      "build-personal-prompt-library",
      "ai-concept-learning-framework",
      // 다듬는 면 (옛 Stage 3)
      "what-llms-are-good-and-bad-at",
      "hallucination-verification",
      "checks-before-trusting-ai-output",
      "fallback-strategy-when-ai-fails",
      "privacy-and-academic-ethics",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Perplexity", "Markdown"],
    nextStageSlug: "stage-3-collaborate",
    weekInMvpPath: 1,
    introEssaySlug: "stage-2-intro",
    outroEssaySlug: "stage-2-outro",
  },
  {
    id: "stage-3",
    slug: "stage-3-collaborate",
    order: 3,
    label: "AI와 함께 일하다",
    titleKo: "Stage 3 · AI와 함께 일하다",
    titleEn: "Collaborate with AI",
    positionChange: "AI를 보조로 두고 산출물 생산",
    deliverable: "자동화·콘텐츠·분석 산출물 1개",
    shortDescription: "보고서·콘텐츠·데이터 분석을 AI와 함께 운영해, 반복 가능한 파이프라인 1개를 만든다.",
    longDescription:
      "AI를 도구에서 '동료'로 격상시키는 단계. 업무 자동화(3a), 콘텐츠·미디어 파이프라인(3b), 데이터 분석(3c) 세 갈래로 나뉘며, 각 갈래에서 한 가지 이상 자기 도메인 산출물을 만든다. 개별 파이프라인을 넘어 재사용 어시스턴트로 묶고, 여러 파이프라인을 한 루틴으로 오케스트레이션하고, 자동화의 ROI까지 따져 보는 — 같은 패턴을 다른 업무에도 옮겨 쓸 수 있는 수준이 목표.",
    level: "beginner",
    estimatedHours: 17,
    targetJourneys: ["practitioner", "creator", "founder", "starter", "ai-native"],
    outcomes: [
      "보고서·회의록·리서치·블로그 같은 반복 업무를 AI 파이프라인으로 운영한다",
      "반복 업무를 재사용 어시스턴트로 묶고 여러 파이프라인을 한 루틴으로 엮는다",
      "콘텐츠·미디어 워크플로우(쇼츠·디자인·영상·썸네일)를 자기 채널에 적용한다",
      "SQL·CRM·대시보드·A/B 테스트 결과를 AI 보조로 분석·해석한다",
      "자동화의 비용과 ROI를 숫자로 따져 어디에 투자할지 판단한다",
    ],
    topics: ["업무 자동화", "재사용 어시스턴트·오케스트레이션", "콘텐츠 파이프라인", "데이터·분석", "자동화 ROI"],
    lessonSlugs: [
      "automate-report-drafts",
      "meeting-notes-pipeline",
      "research-workflow",
      "blog-writing-pipeline",
      "custom-gpt-builder",
      "multi-workflow-orchestration",
      "cost-estimation-and-roi-by-task",
      "blog-to-shorts-pipeline",
      "design-visual-prompt-system",
      "youtube-script-research-to-outline",
      "figma-ai-ui-variation-workflow",
      "thumbnail-and-title-ab-test",
      "local-business-content-calendar",
      "sql-with-ai-verification",
      "crm-segmentation-with-ai",
      "dashboard-narrative-and-qa",
      "ab-test-decision-memo",
    ],
    subGroups: [
      {
        id: "3a",
        label: "업무 자동화",
        shortDescription: "보고서·회의록·리서치·글쓰기를 AI 파이프라인으로 묶고, 재사용 어시스턴트·오케스트레이션·ROI까지 다룬다.",
        deliverable: "반복 업무 1개 자동화",
        lessonSlugs: [
          "automate-report-drafts",
          "meeting-notes-pipeline",
          "research-workflow",
          "blog-writing-pipeline",
          "custom-gpt-builder",
          "multi-workflow-orchestration",
          "cost-estimation-and-roi-by-task",
        ],
      },
      {
        id: "3b",
        label: "콘텐츠·미디어",
        shortDescription: "롱폼·쇼츠·이미지·영상·썸네일을 AI로 빠르게 변형한다.",
        deliverable: "콘텐츠 파이프라인 1개",
        lessonSlugs: [
          "blog-to-shorts-pipeline",
          "design-visual-prompt-system",
          "youtube-script-research-to-outline",
          "figma-ai-ui-variation-workflow",
          "thumbnail-and-title-ab-test",
          "local-business-content-calendar",
        ],
      },
      {
        id: "3c",
        label: "데이터·분석",
        shortDescription: "SQL·CRM·대시보드 숫자를 AI 보조로 해석하고 결정을 만든다.",
        deliverable: "데이터 산출물 1개",
        lessonSlugs: [
          "sql-with-ai-verification",
          "crm-segmentation-with-ai",
          "dashboard-narrative-and-qa",
          "ab-test-decision-memo",
        ],
      },
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Midjourney", "Python", "Excel"],
    nextStageSlug: "stage-4-coding-agent",
    weekInMvpPath: 2,
    introEssaySlug: "stage-3-intro",
    outroEssaySlug: "stage-3-outro",
  },
  {
    id: "stage-4",
    slug: "stage-4-coding-agent",
    order: 4,
    label: "AI에게 일감을 주다",
    titleKo: "Stage 4 · AI에게 일감을 주다",
    titleEn: "Delegate to Coding Agent",
    positionChange: "AI를 위임 동료로 코딩 시킨다",
    deliverable: "AI 페어로 만든 PR 1개",
    shortDescription: "코딩 에이전트를 페어로 두고 이슈→계획→테스트→PR까지 한 사이클을 돌린다.",
    longDescription:
      "여기서 학습자의 위치가 결정적으로 변한다. 지금까지 'AI를 보조로' 썼다면, 이 stage에서 'AI를 위임 동료로' 쓴다 — 나는 개발자, AI는 페어. 코딩 에이전트 셋업, 이슈→AI 브리프 변환, 코드베이스 읽히기, 구현 계획, 테스트 작성, 버그 재현·수정, AI가 만든 PR 리뷰, 그리고 CLAUDE.md 4원칙·hooks 자동 게이트·서브에이전트 설계·하네스 엔지니어링 로드맵으로 매듭짓는다. 빌더 트랙의 시작점.",
    level: "intermediate",
    estimatedHours: 19,
    targetJourneys: ["engineer", "founder", "practitioner", "ai-native"],
    outcomes: [
      "코딩 에이전트의 권한·규약을 자기 프로젝트에 안전하게 깐다",
      "이슈를 AI 브리프로 변환해 첫 시도 정확도를 끌어올린다",
      "계획→테스트→수정→리뷰의 한 사이클을 AI와 함께 돈다",
      "hooks 자동 게이트와 서브에이전트로 작업을 안전하게 키운다",
      "CLAUDE.md 4원칙·하네스 로드맵으로 자기 작업 환경을 평가·개선한다",
    ],
    topics: [
      "에이전트 권한·CLAUDE.md",
      "이슈→AI 브리프",
      "코드베이스 컨텍스트",
      "구현 계획·테스트",
      "버그 재현·PR 리뷰",
      "Hooks 자동 게이트",
      "서브에이전트 설계",
      "하네스 엔지니어링",
    ],
    lessonSlugs: [
      "coding-agent-setup",
      "github-issue-to-ai-brief",
      "letting-ai-read-codebase",
      "plan-with-ai",
      "write-tests-with-coding-agent",
      "bug-reproduction-loop",
      "pr-review-with-ai",
      "claude-md-four-principles",
      "agent-hooks-automation",
      "subagent-context-design",
      "harness-engineering-roadmap",
    ],
    recommendedTools: ["Claude Code", "Codex CLI", "GitHub", "Playwright"],
    nextStageSlug: "stage-5-build-systems",
    weekInMvpPath: 3,
    introEssaySlug: "stage-4-intro",
    outroEssaySlug: "stage-4-outro",
  },
  {
    id: "stage-5",
    slug: "stage-5-build-systems",
    order: 5,
    label: "AI 시스템을 만들다",
    titleKo: "Stage 5 · AI 시스템을 만들다",
    titleEn: "Build AI Systems",
    positionChange: "AI가 부품인 시스템 작동",
    deliverable: "챗봇 / RAG / Agent 중 1개",
    shortDescription: "API·RAG·Agent 세 갈래로 AI를 부품으로 박은 시스템을 직접 만들고 작동시킨다.",
    longDescription:
      "Stage 4와 학습자의 위치가 또 한 번 바뀐다. 이제 나는 시스템 빌더, AI는 부품. 5a는 API로 AI를 호출하는 앱(스트리밍·구조화·저장), 5b는 내 문서를 알고 답하는 RAG(임베딩·청킹·검색·인용), 5c는 도구를 쓰고 결정하는 Agent(Function Calling·루프·권한·인젝션 방어·Ralph Loop). 셋 다 깊게 가도 좋고, 자기 도메인에 가장 가까운 한 갈래만 끝까지 가도 좋다.",
    level: "intermediate",
    estimatedHours: 22,
    targetJourneys: ["engineer", "founder", "ai-native"],
    outcomes: [
      "AI API를 안전하게 앱에 연결하고 스트리밍·구조화 UX를 구현한다",
      "사용자 인증·세션과 장기 기억으로 앱을 \"누가 쓰는지 아는\" 제품으로 만든다",
      "내 문서에 인용으로 답하는 RAG 파이프라인을 만든다",
      "도구를 쓰고 멈출 줄 아는 에이전트를 권한·안전장치와 함께 설계한다",
      "도구를 MCP 서버로 표준화해 여러 클라이언트에서 재사용한다",
    ],
    topics: [
      "AI API·서버 라우트",
      "스트리밍·구조화 출력",
      "대화 저장·인증·장기 기억",
      "임베딩·청킹",
      "벡터 검색·인용",
      "Function Calling·Agent Loop",
      "권한·인젝션 방어",
      "MCP 서버",
      "Ralph Loop · 자율 코딩",
    ],
    lessonSlugs: [
      "connect-ai-api",
      "streaming-response-ui",
      "structured-output-handling",
      "conversation-storage-design",
      "auth-and-user-sessions",
      "long-term-memory-state",
      "understanding-embeddings",
      "document-chunking-strategy",
      "vector-search-basics",
      "grounded-rag-answers",
      "function-calling",
      "mini-agent-loop",
      "tool-permission-safeguards",
      "prompt-injection-defense",
      "build-mcp-server",
      "ralph-loop-codex-goal",
    ],
    subGroups: [
      {
        id: "5a",
        label: "API로 AI 부르기",
        shortDescription: "AI API를 안전하게 앱에 붙이고 스트리밍·구조화·저장·인증·장기 기억까지.",
        deliverable: "API 호출하는 앱 1개",
        lessonSlugs: [
          "connect-ai-api",
          "streaming-response-ui",
          "structured-output-handling",
          "conversation-storage-design",
          "auth-and-user-sessions",
          "long-term-memory-state",
        ],
      },
      {
        id: "5b",
        label: "AI에게 지식 주기 — RAG",
        shortDescription: "내 문서를 임베딩·검색해 인용으로 답하는 시스템을 만든다.",
        deliverable: "내 문서 RAG 1개",
        lessonSlugs: [
          "understanding-embeddings",
          "document-chunking-strategy",
          "vector-search-basics",
          "grounded-rag-answers",
        ],
      },
      {
        id: "5c",
        label: "AI에게 행동 주기 — Agent",
        shortDescription: "도구를 호출하고 권한·안전장치 안에서 자율 루프를 돌린다.",
        deliverable: "도구 쓰는 에이전트 1개",
        lessonSlugs: [
          "function-calling",
          "mini-agent-loop",
          "tool-permission-safeguards",
          "prompt-injection-defense",
          "build-mcp-server",
          "ralph-loop-codex-goal",
        ],
      },
    ],
    recommendedTools: [
      "Next.js",
      "Vercel",
      "OpenAI / Anthropic SDK",
      "pgvector / Pinecone / Chroma",
      "Claude Tools / MCP",
    ],
    nextStageSlug: "stage-6-operate-and-share",
    weekInMvpPath: 5,
    introEssaySlug: "stage-5-intro",
    outroEssaySlug: "stage-5-outro",
  },
  {
    id: "stage-6",
    slug: "stage-6-operate-and-share",
    order: 6,
    label: "시스템을 운영하다",
    titleKo: "Stage 6 · 시스템을 운영하다",
    titleEn: "Operate Systems",
    positionChange: "안 무너지게 굴리고 세상에 내놓는다",
    deliverable: "운영 SLO + 공개된 URL + 회고",
    shortDescription: "Eval·정책·비용 루프로 운영하고, 캡스톤·포트폴리오·Skill로 세상에 내놓는다.",
    longDescription:
      "만든 게 작동했다 ≠ 운영된다. 그리고 공개는 단순히 '링크를 올리는' 게 아니라 피드백을 받는 일이다. 이 단계는 두 축을 같이 간다. 운영 축은 PR Eval 게이트·LLM 관측·에이전트 실패 패턴·MCP 운영·PM Eval·사용자 피드백·정책·비용·토큰 관리. 공유 축은 제품 브리프·랜딩·가격·캡스톤(범위·빌드·런칭)·첫 사용자 모집·Skill 패키징·포트폴리오 회고. 끝나는 시점에 운영 SLO 한 장과 공개된 URL, 그리고 회고 글 하나가 손에 남는다.",
    level: "advanced",
    estimatedHours: 30,
    targetJourneys: ["practitioner", "creator", "founder", "engineer", "starter", "ai-native"],
    outcomes: [
      "AI 코드 PR에 Eval 게이트를 박고 프롬프트 회귀를 관측한다",
      "에이전트 실패 패턴을 미리 알고 guardrail로 예방한다",
      "MCP 서버를 운영 가능한 상태로 관리한다",
      "내부 Eval과 사용자 피드백으로 제품의 진짜 신호를 모은다",
      "팀 AI 사용 정책 + 비용·토큰 관리 체계를 잡는다",
      "AI 제품 브리프 + 랜딩 + 가격을 한 묶음으로 설계한다",
      "캡스톤 범위를 4주 안에 끝낼 크기로 압축해 빌드 루프를 돈다",
      "런칭 후 첫 사용자 5명을 직접 찾아 피드백을 받는다",
      "쌓은 노하우를 재사용 Skill로 패키징해 자산화한다",
      "공개된 URL + 회고 글로 자기 포트폴리오를 만든다",
    ],
    topics: [
      "Eval 게이트·LLM 관측",
      "에이전트 실패 패턴",
      "MCP 서버 운영",
      "PM 품질 평가·사용자 피드백",
      "팀 AI 정책·비용",
      "AI 제품 브리프·랜딩·가격",
      "캡스톤 범위·빌드·런칭",
      "첫 사용자 모집",
      "Skill 패키징",
      "포트폴리오·회고",
    ],
    lessonSlugs: [
      // 운영 축 (옛 Stage 7)
      "evals-for-ai-coded-prs",
      "llm-observability-and-regression",
      "agent-failure-patterns",
      "mcp-production-patterns",
      "ai-output-eval-for-pms",
      "user-feedback-collection-for-ai-products",
      "responsible-ai-policy-template",
      "ai-app-cost-and-usage",
      "claude-code-token-saving",
      // 공유 축 (옛 Stage 8)
      "ai-product-brief",
      "landing-page-for-ai-product",
      "pricing-and-monetization",
      "capstone-scope-selection",
      "capstone-build-loop",
      "capstone-plan-and-launch",
      "early-user-recruitment-for-ai-products",
      "claude-skills-authoring",
      "portfolio-and-retrospective",
    ],
    recommendedTools: ["Evals SDK", "Promptfoo", "Langfuse", "Framer", "Vercel", "Stripe", "GitHub"],
    nextStageSlug: null,
    weekInMvpPath: 7,
    introEssaySlug: "stage-6-intro",
    outroEssaySlug: "stage-6-outro",
  },
];
