// v0.4 — 8 Stage 데이터. 학습자 수직 진척 사다리.
// 매핑 원본: ~/.claude/plans/v0.4-stage-redesign.md (2026-05-16 확정).
import type { Stage } from "@/lib/types";

export const stages: Stage[] = [
  {
    id: "stage-1",
    slug: "stage-1-meet",
    order: 1,
    label: "AI와 만나다",
    titleKo: "Stage 1 · AI와 만나다",
    titleEn: "Meet AI",
    positionChange: "AI 도구 켜고 첫 대화",
    deliverable: "매일 쓰는 AI 도구 1개",
    shortDescription: "AI 도구 계정·터미널·판단 체크리스트로 매일 쓰는 AI 1개를 자기 일에 들여놓는다.",
    longDescription:
      "AI Builder가 되는 사다리의 첫 칸. 코딩 에이전트가 무엇이고 왜 터미널이 필요한지, AI 도구 계정과 비용을 어떻게 관리하는지, 그리고 AI를 쓰면서 사람으로 남는 판단 기준을 잡는다. 끝나는 시점에 매일 쓰는 AI 도구 1개와 자기 업무용 판단 체크리스트 v1이 손에 남는다.",
    level: "beginner",
    estimatedHours: 7,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "AI 도구 1개를 자기 일에 매일 쓰는 습관을 잡는다",
      "터미널 기본 명령어 10개를 두려움 없이 사용한다",
      "AI 비용을 주간 루프로 모니터링해 청구서 쇼크를 예방한다",
      "어떤 일을 AI에 맡길지 판단하는 개인 기준표를 갖는다",
      "팀에 AI를 들이는 30일 도입 계획을 세운다",
    ],
    topics: [
      "코딩 에이전트와 터미널",
      "AI 도구 계정·비용·모니터링",
      "위임 판단 (AI Fluency Delegation)",
      "팀 도입과 변화 관리",
      "Human-in-the-loop 판단",
    ],
    lessonSlugs: [
      "zero-coding-orientation",
      "terminal-first-day",
      "ai-tool-account-and-cost",
      "cost-monitoring-in-production",
      "common-skills-of-future-proof-people",
      "ai-delegation-decision",
      "ai-collaboration-mindset",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Codex CLI", "Claude Code"],
    nextStageSlug: "stage-2-ask",
    weekInMvpPath: 1,
    introEssaySlug: "stage-1-intro",
    outroEssaySlug: "stage-1-outro",
  },
  {
    id: "stage-2",
    slug: "stage-2-ask",
    order: 2,
    label: "AI에게 물어보다",
    titleKo: "Stage 2 · AI에게 물어보다",
    titleEn: "Ask AI",
    positionChange: "의도한 답을 일관되게 끌어낸다",
    deliverable: "개인 프롬프트 라이브러리",
    shortDescription: "모호한 부탁을 재현 가능한 명세로 바꿔, 같은 답을 일관되게 끌어낸다.",
    longDescription:
      "좋은 프롬프트는 부탁이 아니라 명세(Spec)다. 작업·맥락·제약·출력 형식을 분리해 쓰는 법, 출력 포맷을 강제하는 법, 긴 문서를 안전하게 주입하는 법, 그리고 한 번 쓴 프롬프트를 다시 쓰지 않게 라이브러리화하는 법을 익힌다. 끝나는 시점에 개인 프롬프트 라이브러리 한 벌이 손에 남는다.",
    level: "beginner",
    estimatedHours: 8,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "작업/맥락/제약/출력을 분리해 프롬프트를 쓴다",
      "출력 형식을 강제해 자동화 가능한 결과를 얻는다",
      "긴 문서를 분할해 주입하고 컨텍스트 한계를 다룬다",
      "재사용 가능한 프롬프트 라이브러리를 운영한다",
    ],
    topics: [
      "프롬프트 4축 구조",
      "출력 형식 강제",
      "긴 문서 처리",
      "프롬프트 라이브러리",
      "새 용어 학습 프레임",
    ],
    lessonSlugs: [
      "structure-of-good-prompts",
      "enforcing-output-format",
      "feeding-long-documents",
      "build-personal-prompt-library",
      "ai-concept-learning-framework",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Markdown"],
    nextStageSlug: "stage-3-verify",
    weekInMvpPath: 1,
  },
  {
    id: "stage-3",
    slug: "stage-3-verify",
    order: 3,
    label: "AI의 답을 확인하다",
    titleKo: "Stage 3 · AI의 답을 확인하다",
    titleEn: "Verify AI",
    positionChange: "출력을 검증·의심한다",
    deliverable: "검증 루프 1개",
    shortDescription: "LLM이 잘하는 일·못하는 일을 구분하고, 답을 신뢰하기 전 자기 검증 루프를 돌린다.",
    longDescription:
      "AI의 답이 합리적으로 들릴수록 더 위험할 수 있다. 이 stage에서는 LLM의 구조적 한계, 환각(Hallucination)을 잡는 검증 루프, 신뢰하기 전 5분 체크, 개인정보·저작권 같은 안전 경계를 다룬다. 끝나는 시점에 자기 작업에 적용 가능한 검증 루프 한 벌이 손에 남는다.",
    level: "beginner",
    estimatedHours: 6,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "LLM이 잘하는 일과 못하는 일의 경계를 안다",
      "환각·오류를 잡는 검증 루프를 자기 워크플로우에 박는다",
      "프라이버시·저작권 같은 안전 경계를 자기 체크리스트로 갖는다",
    ],
    topics: [
      "LLM 능력의 한계",
      "환각 검증",
      "신뢰 전 5분 체크 (FOSCB)",
      "프라이버시·윤리",
    ],
    lessonSlugs: [
      "what-llms-are-good-and-bad-at",
      "hallucination-verification",
      "checks-before-trusting-ai-output",
      "privacy-and-academic-ethics",
    ],
    recommendedTools: ["Claude", "ChatGPT", "Perplexity"],
    nextStageSlug: "stage-4-collaborate",
    weekInMvpPath: 1,
  },
  {
    id: "stage-4",
    slug: "stage-4-collaborate",
    order: 4,
    label: "AI와 함께 일하다",
    titleKo: "Stage 4 · AI와 함께 일하다",
    titleEn: "Collaborate with AI",
    positionChange: "AI를 보조로 두고 산출물 생산",
    deliverable: "자동화·콘텐츠·분석 산출물 1개",
    shortDescription: "보고서·콘텐츠·데이터 분석을 AI와 함께 운영해, 반복 가능한 파이프라인 1개를 만든다.",
    longDescription:
      "AI를 도구에서 '동료'로 격상시키는 단계. 업무 자동화(4a), 콘텐츠·미디어 파이프라인(4b), 데이터 분석(4c) 세 갈래로 나뉘며, 각 갈래에서 한 가지 이상 자기 도메인 산출물을 만든다. 같은 패턴을 다른 업무에도 옮겨 쓸 수 있는 수준이 목표.",
    level: "beginner",
    estimatedHours: 14,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "explorer"],
    outcomes: [
      "보고서·회의록·리서치·블로그 같은 반복 업무를 AI 파이프라인으로 운영한다",
      "콘텐츠·미디어 워크플로우(쇼츠·디자인·영상·썸네일)를 자기 채널에 적용한다",
      "SQL·CRM·대시보드·A/B 테스트 결과를 AI 보조로 분석·해석한다",
    ],
    topics: ["업무 자동화", "콘텐츠 파이프라인", "데이터·분석", "팀 단위 협업"],
    lessonSlugs: [
      "automate-report-drafts",
      "meeting-notes-pipeline",
      "research-workflow",
      "blog-writing-pipeline",
      "blog-to-shorts-pipeline",
      "design-visual-prompt-system",
      "youtube-script-research-to-outline",
      "figma-ai-ui-variation-workflow",
      "thumbnail-and-title-ab-test",
      "local-business-content-calendar",
      "sql-with-ai-verification",
      "crm-segmentation-with-ai",
      "dashboard-narrative-and-qa",
      "ab-test-decision-memo",
    ],
    subGroups: [
      {
        id: "4a",
        label: "업무 자동화",
        shortDescription: "보고서·회의록·리서치·글쓰기를 AI 파이프라인으로 묶는다.",
        deliverable: "반복 업무 1개 자동화",
        lessonSlugs: [
          "automate-report-drafts",
          "meeting-notes-pipeline",
          "research-workflow",
          "blog-writing-pipeline",
        ],
      },
      {
        id: "4b",
        label: "콘텐츠·미디어",
        shortDescription: "롱폼·쇼츠·이미지·영상·썸네일을 AI로 빠르게 변형한다.",
        deliverable: "콘텐츠 파이프라인 1개",
        lessonSlugs: [
          "blog-to-shorts-pipeline",
          "design-visual-prompt-system",
          "youtube-script-research-to-outline",
          "figma-ai-ui-variation-workflow",
          "thumbnail-and-title-ab-test",
          "local-business-content-calendar",
        ],
      },
      {
        id: "4c",
        label: "데이터·분석",
        shortDescription: "SQL·CRM·대시보드 숫자를 AI 보조로 해석하고 결정을 만든다.",
        deliverable: "데이터 산출물 1개",
        lessonSlugs: [
          "sql-with-ai-verification",
          "crm-segmentation-with-ai",
          "dashboard-narrative-and-qa",
          "ab-test-decision-memo",
        ],
      },
    ],
    recommendedTools: ["Claude", "ChatGPT", "Notion", "Midjourney", "Python", "Excel"],
    nextStageSlug: "stage-5-delegate",
    weekInMvpPath: 2,
  },
  {
    id: "stage-5",
    slug: "stage-5-delegate",
    order: 5,
    label: "AI에게 일감을 주다",
    titleKo: "Stage 5 · AI에게 일감을 주다",
    titleEn: "Delegate to AI",
    positionChange: "AI를 위임 동료로 코딩 시킨다",
    deliverable: "AI 페어로 만든 PR 1개",
    shortDescription: "코딩 에이전트를 페어로 두고 이슈→계획→테스트→PR까지 한 사이클을 돌린다.",
    longDescription:
      "여기서 학습자의 위치가 결정적으로 변한다. 지금까지 'AI를 보조로' 썼다면, 이 stage에서 'AI를 위임 동료로' 쓴다 — 나는 개발자, AI는 페어. 코딩 에이전트 셋업, 이슈→AI 브리프 변환, 코드베이스 읽히기, 구현 계획, 테스트 작성, 버그 재현·수정, 그리고 CLAUDE.md 4원칙과 하네스 엔지니어링 6단계 로드맵으로 매듭짓는다.",
    level: "intermediate",
    estimatedHours: 14,
    targetJourneys: ["engineer", "founder", "practitioner"],
    outcomes: [
      "코딩 에이전트의 권한·규약을 자기 프로젝트에 안전하게 깐다",
      "이슈를 AI 브리프로 변환해 첫 시도 정확도를 끌어올린다",
      "계획→테스트→수정→회귀의 한 사이클을 AI와 함께 돈다",
      "CLAUDE.md 4원칙·하네스 6단계로 자기 작업 환경을 평가·개선한다",
    ],
    topics: [
      "에이전트 권한·CLAUDE.md",
      "이슈→AI 브리프",
      "코드베이스 컨텍스트",
      "구현 계획·테스트",
      "버그 재현 루프",
      "하네스 엔지니어링",
    ],
    lessonSlugs: [
      "coding-agent-setup",
      "github-issue-to-ai-brief",
      "letting-ai-read-codebase",
      "plan-with-ai",
      "write-tests-with-coding-agent",
      "bug-reproduction-loop",
      "claude-md-four-principles",
      "harness-engineering-roadmap",
    ],
    recommendedTools: ["Claude Code", "Codex CLI", "GitHub", "Playwright"],
    nextStageSlug: "stage-6-build",
    weekInMvpPath: 3,
  },
  {
    id: "stage-6",
    slug: "stage-6-build",
    order: 6,
    label: "AI 시스템을 만들다",
    titleKo: "Stage 6 · AI 시스템을 만들다",
    titleEn: "Build AI Systems",
    positionChange: "AI가 부품인 시스템 작동",
    deliverable: "챗봇 / RAG / Agent 중 1개",
    shortDescription: "API·RAG·Agent 세 갈래로 AI를 부품으로 박은 시스템을 직접 만들고 작동시킨다.",
    longDescription:
      "Stage 5와 학습자의 위치가 또 한 번 바뀐다. 이제 나는 시스템 빌더, AI는 부품. 6a는 API로 AI를 호출하는 앱(스트리밍·구조화·저장), 6b는 내 문서를 알고 답하는 RAG(임베딩·청킹·검색·인용), 6c는 도구를 쓰고 결정하는 Agent(Function Calling·루프·권한·인젝션 방어·Ralph Loop). 셋 다 깊게 가도 좋고, 자기 도메인에 가장 가까운 한 갈래만 끝까지 가도 좋다.",
    level: "intermediate",
    estimatedHours: 18,
    targetJourneys: ["engineer", "founder"],
    outcomes: [
      "AI API를 안전하게 앱에 연결하고 스트리밍·구조화 UX를 구현한다",
      "내 문서에 인용으로 답하는 RAG 파이프라인을 만든다",
      "도구를 쓰고 멈출 줄 아는 에이전트를 권한·안전장치와 함께 설계한다",
    ],
    topics: [
      "AI API·서버 라우트",
      "스트리밍 UI",
      "구조화 출력",
      "대화 저장",
      "임베딩·청킹",
      "벡터 검색·인용",
      "Function Calling·Agent Loop",
      "권한·인젝션 방어",
      "Ralph Loop · 자율 코딩",
    ],
    lessonSlugs: [
      "connect-ai-api",
      "streaming-response-ui",
      "structured-output-handling",
      "conversation-storage-design",
      "understanding-embeddings",
      "document-chunking-strategy",
      "vector-search-basics",
      "grounded-rag-answers",
      "function-calling",
      "mini-agent-loop",
      "tool-permission-safeguards",
      "prompt-injection-defense",
      "ralph-loop-codex-goal",
    ],
    subGroups: [
      {
        id: "6a",
        label: "API로 AI 부르기",
        shortDescription: "AI API를 안전하게 앱에 붙이고 스트리밍·구조화·저장까지.",
        deliverable: "API 호출하는 앱 1개",
        lessonSlugs: [
          "connect-ai-api",
          "streaming-response-ui",
          "structured-output-handling",
          "conversation-storage-design",
        ],
      },
      {
        id: "6b",
        label: "AI에게 지식 주기 — RAG",
        shortDescription: "내 문서를 임베딩·검색해 인용으로 답하는 시스템을 만든다.",
        deliverable: "내 문서 RAG 1개",
        lessonSlugs: [
          "understanding-embeddings",
          "document-chunking-strategy",
          "vector-search-basics",
          "grounded-rag-answers",
        ],
      },
      {
        id: "6c",
        label: "AI에게 행동 주기 — Agent",
        shortDescription: "도구를 호출하고 권한·안전장치 안에서 자율 루프를 돌린다.",
        deliverable: "도구 쓰는 에이전트 1개",
        lessonSlugs: [
          "function-calling",
          "mini-agent-loop",
          "tool-permission-safeguards",
          "prompt-injection-defense",
          "ralph-loop-codex-goal",
        ],
      },
    ],
    recommendedTools: [
      "Next.js",
      "Vercel",
      "OpenAI / Anthropic SDK",
      "pgvector / Pinecone / Chroma",
      "Claude Tools / MCP",
    ],
    nextStageSlug: "stage-7-operate",
    weekInMvpPath: 5,
  },
  {
    id: "stage-7",
    slug: "stage-7-operate",
    order: 7,
    label: "AI 시스템을 운영하다",
    titleKo: "Stage 7 · AI 시스템을 운영하다",
    titleEn: "Operate AI Systems",
    positionChange: "평가·안전·비용 루프 가동",
    deliverable: "운영 SLO 1개",
    shortDescription: "Eval·관측·정책·비용 루프를 깔아, 만든 AI 시스템을 운영 단계로 끌어올린다.",
    longDescription:
      "만든 게 작동했다 ≠ 운영된다. 이 stage에서는 AI가 작성한 코드를 PR 게이트로 검증하는 Eval, 프롬프트를 바꿨을 때 회귀를 잡는 관측, 코드 없이 출력 품질을 평가하는 PM용 Eval, 팀 AI 사용 정책, 그리고 비용·토큰 관리까지 한 묶음으로 다룬다. 끝나는 시점에 자기 시스템의 운영 SLO 한 장이 손에 남는다.",
    level: "advanced",
    estimatedHours: 10,
    targetJourneys: ["engineer", "adopter", "founder", "practitioner"],
    outcomes: [
      "AI 코드 PR에 Eval 게이트를 박는다",
      "프롬프트 회귀를 잡는 관측·로깅 루프를 운영한다",
      "코드 없이 출력 품질을 평가하는 기준을 만든다",
      "팀 AI 사용 정책 + 비용·토큰 관리 체계를 잡는다",
    ],
    topics: [
      "Eval 게이트",
      "LLM 관측·회귀",
      "PM 품질 평가",
      "팀 AI 정책",
      "AI 비용·토큰 절약",
    ],
    lessonSlugs: [
      "evals-for-ai-coded-prs",
      "llm-observability-and-regression",
      "ai-output-eval-for-pms",
      "responsible-ai-policy-template",
      "ai-app-cost-and-usage",
      "claude-code-token-saving",
    ],
    recommendedTools: ["Evals SDK", "Promptfoo", "Langfuse", "Vercel Analytics"],
    nextStageSlug: "stage-8-share",
    weekInMvpPath: 7,
  },
  {
    id: "stage-8",
    slug: "stage-8-share",
    order: 8,
    label: "AI 시스템을 공유하다",
    titleKo: "Stage 8 · AI 시스템을 공유하다",
    titleEn: "Share AI Systems",
    positionChange: "사용자에게 전달",
    deliverable: "사용자 또는 매출",
    shortDescription: "브리프·랜딩·가격·캡스톤·포트폴리오로, 만든 시스템을 세상에 내놓는다.",
    longDescription:
      "마지막 사다리 칸. AI 제품 브리프, 랜딩 페이지, 가격·수익화, 캡스톤 범위 압축, 빌드 루프, 런칭, 포트폴리오 회고까지. 캡스톤은 학습자 본인 프로젝트이며, 끝나는 시점에 공개된 URL 1개와 회고 글 1개가 손에 남는다.",
    level: "advanced",
    estimatedHours: 14,
    targetJourneys: ["practitioner", "adopter", "creator", "founder", "engineer", "explorer"],
    outcomes: [
      "AI 제품 브리프 + 랜딩 + 가격을 한 묶음으로 설계한다",
      "캡스톤 범위를 4주 안에 끝낼 크기로 압축해 빌드 루프를 돈다",
      "공개된 URL + 회고 글로 자기 포트폴리오를 만든다",
    ],
    topics: [
      "AI 제품 브리프",
      "랜딩 페이지",
      "가격·수익화",
      "캡스톤 범위·빌드",
      "런칭·회고",
      "포트폴리오",
    ],
    lessonSlugs: [
      "ai-product-brief",
      "landing-page-for-ai-product",
      "pricing-and-monetization",
      "capstone-scope-selection",
      "capstone-build-loop",
      "capstone-plan-and-launch",
      "portfolio-and-retrospective",
    ],
    recommendedTools: ["Framer", "Vercel", "Stripe", "GitHub", "Notion"],
    nextStageSlug: null,
    weekInMvpPath: 8,
  },
];
