// 문자열 아이콘 이름을 lucide-react 컴포넌트로 해석한다 (MDX에서 문자열로 명시)
import {
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clipboard,
  ClipboardCheck,
  Code,
  Compass,
  Database,
  Eye,
  FileText,
  Flame,
  Folder,
  GitBranch,
  Grid3x3,
  Image as ImageIcon,
  Layers,
  Lightbulb,
  Link as LinkIcon,
  List,
  Lock,
  MessageSquare,
  PenTool,
  Rocket,
  RotateCw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Smartphone,
  Target,
  Terminal,
  Users,
  Workflow,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  "bar-chart": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  boxes: Boxes,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  code: Code,
  compass: Compass,
  database: Database,
  eye: Eye,
  "file-text": FileText,
  flame: Flame,
  folder: Folder,
  "git-branch": GitBranch,
  grid: Grid3x3,
  image: ImageIcon,
  layers: Layers,
  lightbulb: Lightbulb,
  link: LinkIcon,
  list: List,
  lock: Lock,
  "message-square": MessageSquare,
  "pen-tool": PenTool,
  rocket: Rocket,
  "rotate-cw": RotateCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  smartphone: Smartphone,
  target: Target,
  terminal: Terminal,
  users: Users,
  workflow: Workflow,
  "x-circle": XCircle,
  zap: Zap,
};

export function Icon({
  name,
  size = 16,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Cmp = ICONS[name] ?? Circle;
  return (
    <Cmp width={size} height={size} className={className} aria-hidden />
  );
}
